node {

    def imageTag = "peterngtr/rest-demo:${env.BUILD_NUMBER}"
    def dockerHome = tool 'myDocker'

    stage("Initializing test") {
        cleanWs();
        checkout scm;
        sh 'git reset --hard'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }

    stage("Building Images test") {
        // sh "sudo docker"
        // sh "sudo docker ps"
        // sh "sudo service docker status"
        sh "sudo dockerd"
        // sh "sudo systemctl status docker"
        sh "sudo docker build -t ${imageTag} -f docker/Dockerfile ."
    }

    stage("Running Tests") {
        try {
            sh "jenkins/run-tests.sh ${env.BUILD_NUMBER}"
        }
        finally {
            sh "ls report/"
            allure includeProperties: false, jdk: '', results: [[path: 'report']]
        }
    }


}
