node {
    def dockerHome = tool 'myDocker'

    stage("Initializing") {
        checkout scm
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }

    stage("Testing") {
        echo "Hello world"
        sh "docker version"
        echo "End testing stage"
    }

    stage("Building Images") {

        def customImage = docker.build("my-image:${env.BUILD_ID}")

        customImage.inside {
            sh 'echo "Hello world from docker"'
        }
    }

    stage('Example') {
        sh 'echo myCustomVar = $myCustomVar'
    }
}