node {
    def dockerHome = tool 'myDocker'

    // stage("Initializing") {
    //     env.PATH = "${dockerHome}/bin:${env.PATH}"
    // }

    stage("Building Images") {
        checkout scm

        def customImage = docker.build("my-image:${env.BUILD_ID}")

        customImage.inside {
            sh 'echo "Hello world"'
        }
    }

    stage('Example') {
        echo "Hello world"
        sh 'echo myCustomVar = $myCustomVar'
    }
}