pipeline {
    agent {
        docker { image 'selenium/node-chrome' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}